on:
  push:
    branches: ["master"]

  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      node-version: 16.x

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Node setup (latest LTS)
        uses: actions/setup-node@v3

        with:
          node-version: ${{ env.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Webpack build

        run: |
          npm install
          npx webpack --mode production

      - name: Compute short SHA
        run: echo SHORT_SHA=`echo ${GITHUB_SHA::7}` >> $GITHUB_ENV

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          full_commit_message: Redeploy for ${{ env.SHORT_SHA }}
